version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:

  build-and-test-javascript:
     
     docker:
       - image: cimg/node:14.20.0
     steps:
       - checkout
       - run:
           name: install dependencies
           command: cd test_javascript && npm install
     
       - run:
           name: run tests
           command: cd test_javascript && npm run test
workflows:
  sample:
    jobs:
     
      - build-and-test-javascript
